[meta]
name = "Start"
author = "taennan"

[[sprites]]
position = [0.0, 0.0, 0.0]
size = [0.4, 0.4]
texture_path = "assets/albatross-light.jpg"

[[sprites]]
position = [0.5, 0.5, 0.0]
size = [0.4, 0.4]
texture_path = "assets/albatross-dark.jpg"

#[tilemap]
#texture_path = "assets/tilemap.png"

#[[tilemap.chunks]]
#position = [0, 0, 0]
#tiles = [0, 0, 1, 2, 65, 2]
